export const CONFIG = {
    WORLD_SIZE: 6000,
    PLAYER_SPEED: 350,
    CHIGGA_SPEED: 280,
    RECRUIT_RANGE: 200,
    TERRITORY_CAPTURE_TIME: 6000,
    SPAWN_INTERVAL: 10000,
    BASE_ARMY_LIMIT: 3,
    MAX_ARMY_LIMIT: 10,
    BASE_TURF_CAPACITY: 3,
    MAX_TURF_CAPACITY: 10,
    TURF_BUFF_MULTIPLIER: 2.5,
    ENEMY_GROWTH_RATE: 0.3,
    FACTIONS: {
        NEUTRAL: 'neutral',
        PLAYER: 'player',
        BLUE: 'blue',
        GREEN: 'green',
        PURPLE: 'purple',
        ORANGE: 'orange',
        WILD: 'wild'
    },
    COLORS: {
        NEUTRAL: 0xcccccc,
        PLAYER: 0xff3333,
        BLUE: 0x3333ff,
        GREEN: 0x33ff33,
        PURPLE: 0xbb33ff,
        ORANGE: 0xff8800,
        WILD: 0xff6600
    },

    // --- Stage definitions ---
    STAGES: [
        {
            level: 1,
            name: 'The Forearm',
            turfs: 5,
            enemies: 2,
            neutralChiggas: 20,
            decorDensity: 'low',
            description: 'A patch of dry forearm skin. Light resistance.',
            enemyRecruitRate: 0.001,
            enemyGrowthInterval: 18000,
            enemyMaxFollowers: 4,
            bossScale: 1.0,
            skinTint: 0xd4956a,
            ambientOverlay: null,
            hairDensity: 'sparse',
            bossName: 'FLEA KING',
            bossDesc: 'A bloated flea lord. Capture all turfs to summon him.',
            weather: null,
            bgTexture: 'skin-texture'
        },
        {
            level: 2,
            name: 'The Shin',
            turfs: 8,
            enemies: 3,
            neutralChiggas: 30,
            decorDensity: 'medium',
            description: 'Rough shin skin with bumps and bruises.',
            enemyRecruitRate: 0.003,
            enemyGrowthInterval: 12000,
            enemyMaxFollowers: 6,
            bossScale: 1.6,
            skinTint: 0xffffff,       
            ambientOverlay: 0x001133, // cool blue night tint
            hairDensity: 'medium',
            bossName: 'TICK TYRANT',
            bossDesc: 'A scarred tick warlord. He\'s watching from the dark.',
            weather: 'rain',
            bgTexture: 'skin-brown'
        },
        {
            level: 3,
            name: 'The Back',
            turfs: 12,
            enemies: 4,
            neutralChiggas: 40,
            decorDensity: 'high',
            description: 'Vast pale back skin. Heavily tattooed and scarred.',
            enemyRecruitRate: 0.006,
            enemyGrowthInterval: 8000,
            enemyMaxFollowers: 8,
            bossScale: 2.4,
            skinTint: 0xffffff,       
            ambientOverlay: 0x220000, // blood-red war tint
            hairDensity: 'dense',
            bossName: 'MITE OVERLORD',
            bossDesc: 'The ancient parasite god. Prepare yourself.',
            weather: null,
            bgTexture: 'skin-pale'
        },
        {
            level: 4,
            name: 'The Foot',
            turfs: 15,
            enemies: 5,
            neutralChiggas: 50,
            decorDensity: 'extreme',
            description: 'Dirty, calloused foot skin. A brutal battlefield.',
            enemyRecruitRate: 0.01,
            enemyGrowthInterval: 6000,
            enemyMaxFollowers: 10,
            bossScale: 3.0,
            skinTint: 0x8a7f72,       // Dirty, greyish-brown skin
            ambientOverlay: 0x332211, // dirty grime overlay
            hairDensity: 'sparse',
            bossName: 'LICE LORD',
            bossDesc: 'The translucent monarch of dirty crevices. Spawns sticky nits and crawls along hair follicles.',
            weather: 'snow',
            bgTexture: 'skin-texture'
        },
        {
            level: 5,
            name: 'The Hound',
            turfs: 18,
            enemies: 6,
            neutralChiggas: 60,
            decorDensity: 'extreme',
            description: 'The thick fur of a stray dog. A wild jungle of hair.',
            enemyRecruitRate: 0.015,
            enemyGrowthInterval: 4000,
            enemyMaxFollowers: 12,
            bossScale: 3.8,
            skinTint: 0xffffff,       
            ambientOverlay: null,
            hairDensity: 'extreme',
            bossName: 'TICK TWINS',
            bossDesc: 'Two giant, blood-gorged tick siblings invading from both sides of the screen!',
            weather: 'rain',
            bgTexture: 'skin-dog'
        },
        {
            level: 6,
            name: 'The Grass Lawn',
            turfs: 0,
            enemies: 0,
            neutralChiggas: 70,
            decorDensity: 'high',
            description: 'The green lawn beyond the hosts. A dangerous new frontier.',
            enemyRecruitRate: 0,
            enemyGrowthInterval: 0,
            enemyMaxFollowers: 0,
            bossScale: 4.2,
            skinTint: 0xffffff,
            ambientOverlay: 0x112200, // grass green war tint
            hairDensity: 'none',
            bossName: 'ROACH CZAR',
            bossDesc: 'The final titan of the lawn. Spits acidic mucus and breeds endless swarms.',
            weather: null,
            bgTexture: 'grass-lawn'
        }
    ]
};