export const LEGENDARY_ITEM_PRICE_USD = 0.99;
export const LEGENDARY_ITEM_PRICE_LABEL = '$0.99';
export const LEGENDARY_ITEM_CATEGORY = 'legendary_chigga_wear';

export const LEGENDARY_PURCHASE_ENTITIES = {
    skin_chigga_bball_team_black: {
        skinId: "skin_chigga_bball_team_black",
        productId: "chigga_wear_skin_chigga_bball_team_black",
        googlePlayProductId: "chigga_wear_skin_chigga_bball_team_black",
        steamProductId: "chigga_wear_skin_chigga_bball_team_black",
        steamItemDefId: 1001,
        title: "Chigga B-Ball Team Black",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_bball_team_black.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    skin_chigga_bball_team_blue: {
        skinId: "skin_chigga_bball_team_blue",
        productId: "chigga_wear_skin_chigga_bball_team_blue",
        googlePlayProductId: "chigga_wear_skin_chigga_bball_team_blue",
        steamProductId: "chigga_wear_skin_chigga_bball_team_blue",
        steamItemDefId: 1002,
        title: "Chigga B-Ball Team Blue",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_bball_team_blue.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    skin_chigga_bball_team_green: {
        skinId: "skin_chigga_bball_team_green",
        productId: "chigga_wear_skin_chigga_bball_team_green",
        googlePlayProductId: "chigga_wear_skin_chigga_bball_team_green",
        steamProductId: "chigga_wear_skin_chigga_bball_team_green",
        steamItemDefId: 1003,
        title: "Chigga B-Ball Team Green",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_bball_team_green.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    skin_chigga_bball_team_purple: {
        skinId: "skin_chigga_bball_team_purple",
        productId: "chigga_wear_skin_chigga_bball_team_purple",
        googlePlayProductId: "chigga_wear_skin_chigga_bball_team_purple",
        steamProductId: "chigga_wear_skin_chigga_bball_team_purple",
        steamItemDefId: 1004,
        title: "Chigga B-Ball Team Purple",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_bball_team_purple.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    skin_chigga_bball_team_red: {
        skinId: "skin_chigga_bball_team_red",
        productId: "chigga_wear_skin_chigga_bball_team_red",
        googlePlayProductId: "chigga_wear_skin_chigga_bball_team_red",
        steamProductId: "chigga_wear_skin_chigga_bball_team_red",
        steamItemDefId: 1005,
        title: "Chigga B-Ball Team Red",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_bball_team_red.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    skin_chigga_fball_team_black: {
        skinId: "skin_chigga_fball_team_black",
        productId: "chigga_wear_skin_chigga_fball_team_black",
        googlePlayProductId: "chigga_wear_skin_chigga_fball_team_black",
        steamProductId: "chigga_wear_skin_chigga_fball_team_black",
        steamItemDefId: 1006,
        title: "Chigga F-Ball Team Black",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_fball_team_black.png",
        description: "A Legendary gridiron fit with heavy team energy and turf-war attitude."
    },
    skin_chigga_fball_team_green: {
        skinId: "skin_chigga_fball_team_green",
        productId: "chigga_wear_skin_chigga_fball_team_green",
        googlePlayProductId: "chigga_wear_skin_chigga_fball_team_green",
        steamProductId: "chigga_wear_skin_chigga_fball_team_green",
        steamItemDefId: 1007,
        title: "Chigga F-Ball Team Green",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_fball_team_green.png",
        description: "A Legendary gridiron fit with heavy team energy and turf-war attitude."
    },
    skin_chigga_fball_team_purple: {
        skinId: "skin_chigga_fball_team_purple",
        productId: "chigga_wear_skin_chigga_fball_team_purple",
        googlePlayProductId: "chigga_wear_skin_chigga_fball_team_purple",
        steamProductId: "chigga_wear_skin_chigga_fball_team_purple",
        steamItemDefId: 1008,
        title: "Chigga F-Ball Team Purple",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_fball_team_purple.png",
        description: "A Legendary gridiron fit with heavy team energy and turf-war attitude."
    },
    skin_chigga_fball_team_red: {
        skinId: "skin_chigga_fball_team_red",
        productId: "chigga_wear_skin_chigga_fball_team_red",
        googlePlayProductId: "chigga_wear_skin_chigga_fball_team_red",
        steamProductId: "chigga_wear_skin_chigga_fball_team_red",
        steamItemDefId: 1009,
        title: "Chigga F-Ball Team Red",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_fball_team_red.png",
        description: "A Legendary gridiron fit with heavy team energy and turf-war attitude."
    },
    skin_chigga_vamp: {
        skinId: "skin_chigga_vamp",
        productId: "chigga_wear_skin_chigga_vamp",
        googlePlayProductId: "chigga_wear_skin_chigga_vamp",
        steamProductId: "chigga_wear_skin_chigga_vamp",
        steamItemDefId: 1010,
        title: "Chigga Vamp",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/chigga_vamp.png",
        description: "A premium night-stalker look with supernatural bite and Legendary drip."
    },
    skin_formal_fine_flea: {
        skinId: "skin_formal_fine_flea",
        productId: "chigga_wear_skin_formal_fine_flea",
        googlePlayProductId: "chigga_wear_skin_formal_fine_flea",
        steamProductId: "chigga_wear_skin_formal_fine_flea",
        steamItemDefId: 1011,
        title: "Formal Fine Flea",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/formal_fine_flea.png",
        description: "A premium formal fit with spy-level polish and boss-room confidence."
    },
    skin_mummified_mite: {
        skinId: "skin_mummified_mite",
        productId: "chigga_wear_skin_mummified_mite",
        googlePlayProductId: "chigga_wear_skin_mummified_mite",
        steamProductId: "chigga_wear_skin_mummified_mite",
        steamItemDefId: 1012,
        title: "Mummified Mite",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/mummified_mite.png",
        description: "A wrapped-up Legendary fit built for ancient mite mayhem."
    },
    skin_pinstripe_plague_boss: {
        skinId: "skin_pinstripe_plague_boss",
        productId: "chigga_wear_skin_pinstripe_plague_boss",
        googlePlayProductId: "chigga_wear_skin_pinstripe_plague_boss",
        steamProductId: "chigga_wear_skin_pinstripe_plague_boss",
        steamItemDefId: 1013,
        title: "Pinstripe Plague Boss",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/pinstripe_plague_boss.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    skin_purple_velour_vandal: {
        skinId: "skin_purple_velour_vandal",
        productId: "chigga_wear_skin_purple_velour_vandal",
        googlePlayProductId: "chigga_wear_skin_purple_velour_vandal",
        steamProductId: "chigga_wear_skin_purple_velour_vandal",
        steamItemDefId: 1014,
        title: "Purple Velour Vandal",
        type: "player",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/purple_velour_vandal.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_lil_vamp_soldier: {
        skinId: "soldier_lil_vamp_soldier",
        productId: "chigga_wear_soldier_lil_vamp_soldier",
        googlePlayProductId: "chigga_wear_soldier_lil_vamp_soldier",
        steamProductId: "chigga_wear_soldier_lil_vamp_soldier",
        steamItemDefId: 2001,
        title: "Lil Vamp Soldier",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/lil_vamp_soldier.png",
        description: "A premium night-stalker look with supernatural bite and Legendary drip."
    },
    soldier_soldier_0007_suit: {
        skinId: "soldier_soldier_0007_suit",
        productId: "chigga_wear_soldier_soldier_0007_suit",
        googlePlayProductId: "chigga_wear_soldier_soldier_0007_suit",
        steamProductId: "chigga_wear_soldier_soldier_0007_suit",
        steamItemDefId: 2002,
        title: "Soldier 0007 Suit",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_0007_suit.png",
        description: "A premium formal fit with spy-level polish and boss-room confidence."
    },
    soldier_soldier_bball_blue: {
        skinId: "soldier_soldier_bball_blue",
        productId: "chigga_wear_soldier_soldier_bball_blue",
        googlePlayProductId: "chigga_wear_soldier_soldier_bball_blue",
        steamProductId: "chigga_wear_soldier_soldier_bball_blue",
        steamItemDefId: 2003,
        title: "Soldier B-Ball Blue",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_bball_blue.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    soldier_soldier_bball_team_flame: {
        skinId: "soldier_soldier_bball_team_flame",
        productId: "chigga_wear_soldier_soldier_bball_team_flame",
        googlePlayProductId: "chigga_wear_soldier_soldier_bball_team_flame",
        steamProductId: "chigga_wear_soldier_soldier_bball_team_flame",
        steamItemDefId: 2004,
        title: "Soldier B-Ball Team Flame",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_bball_team_flame.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    soldier_soldier_bball_team_green: {
        skinId: "soldier_soldier_bball_team_green",
        productId: "chigga_wear_soldier_soldier_bball_team_green",
        googlePlayProductId: "chigga_wear_soldier_soldier_bball_team_green",
        steamProductId: "chigga_wear_soldier_soldier_bball_team_green",
        steamItemDefId: 2005,
        title: "Soldier B-Ball Team Green",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_bball_team_green.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    soldier_soldier_bball_team_purple: {
        skinId: "soldier_soldier_bball_team_purple",
        productId: "chigga_wear_soldier_soldier_bball_team_purple",
        googlePlayProductId: "chigga_wear_soldier_soldier_bball_team_purple",
        steamProductId: "chigga_wear_soldier_soldier_bball_team_purple",
        steamItemDefId: 2006,
        title: "Soldier B-Ball Team Purple",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_bball_team_purple.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    soldier_soldier_bball_team_red: {
        skinId: "soldier_soldier_bball_team_red",
        productId: "chigga_wear_soldier_soldier_bball_team_red",
        googlePlayProductId: "chigga_wear_soldier_soldier_bball_team_red",
        steamProductId: "chigga_wear_soldier_soldier_bball_team_red",
        steamItemDefId: 2007,
        title: "Soldier B-Ball Team Red",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_bball_team_red.png",
        description: "A Legendary court-ready uniform made for running the whole skin league."
    },
    soldier_soldier_franken_flea: {
        skinId: "soldier_soldier_franken_flea",
        productId: "chigga_wear_soldier_soldier_franken_flea",
        googlePlayProductId: "chigga_wear_soldier_soldier_franken_flea",
        steamProductId: "chigga_wear_soldier_soldier_franken_flea",
        steamItemDefId: 2008,
        title: "Soldier Franken Flea",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_franken_flea.png",
        description: "A stitched-up Legendary soldier look with monster-movie bite."
    },
    soldier_soldier_mummy_fit: {
        skinId: "soldier_soldier_mummy_fit",
        productId: "chigga_wear_soldier_soldier_mummy_fit",
        googlePlayProductId: "chigga_wear_soldier_soldier_mummy_fit",
        steamProductId: "chigga_wear_soldier_soldier_mummy_fit",
        steamItemDefId: 2009,
        title: "Soldier Mummy Fit",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_mummy_fit.png",
        description: "A wrapped-up Legendary fit built for ancient mite mayhem."
    },
    soldier_soldier_sour_prince: {
        skinId: "soldier_soldier_sour_prince",
        productId: "chigga_wear_soldier_soldier_sour_prince",
        googlePlayProductId: "chigga_wear_soldier_soldier_sour_prince",
        steamProductId: "chigga_wear_soldier_soldier_sour_prince",
        steamItemDefId: 2010,
        title: "Soldier Sour Prince",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_sour_prince.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_soldier_team_black: {
        skinId: "soldier_soldier_team_black",
        productId: "chigga_wear_soldier_soldier_team_black",
        googlePlayProductId: "chigga_wear_soldier_soldier_team_black",
        steamProductId: "chigga_wear_soldier_soldier_team_black",
        steamItemDefId: 2011,
        title: "Soldier Team Black",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_team_black.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_soldier_team_black_2: {
        skinId: "soldier_soldier_team_black_2",
        productId: "chigga_wear_soldier_soldier_team_black_2",
        googlePlayProductId: "chigga_wear_soldier_soldier_team_black_2",
        steamProductId: "chigga_wear_soldier_soldier_team_black_2",
        steamItemDefId: 2012,
        title: "Soldier Team Black 2",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_team_black_2.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_soldier_team_blue: {
        skinId: "soldier_soldier_team_blue",
        productId: "chigga_wear_soldier_soldier_team_blue",
        googlePlayProductId: "chigga_wear_soldier_soldier_team_blue",
        steamProductId: "chigga_wear_soldier_soldier_team_blue",
        steamItemDefId: 2013,
        title: "Soldier Team Blue",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_team_blue.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_soldier_team_green: {
        skinId: "soldier_soldier_team_green",
        productId: "chigga_wear_soldier_soldier_team_green",
        googlePlayProductId: "chigga_wear_soldier_soldier_team_green",
        steamProductId: "chigga_wear_soldier_soldier_team_green",
        steamItemDefId: 2014,
        title: "Soldier Team Green",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_team_green.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
    soldier_soldier_team_orange: {
        skinId: "soldier_soldier_team_orange",
        productId: "chigga_wear_soldier_soldier_team_orange",
        googlePlayProductId: "chigga_wear_soldier_soldier_team_orange",
        steamProductId: "chigga_wear_soldier_soldier_team_orange",
        steamItemDefId: 2015,
        title: "Soldier Team Orange",
        type: "soldier",
        category: LEGENDARY_ITEM_CATEGORY,
        priceUsd: LEGENDARY_ITEM_PRICE_USD,
        priceLabel: LEGENDARY_ITEM_PRICE_LABEL,
        currency: 'USD',
        consumable: false,
        entitlementType: 'permanent',
        active: true,
        imagePath: "assets/soldier_team_orange.png",
        description: "A premium Legendary cosmetic built for players who want maximum swarm style."
    },
};

export const LEGENDARY_PURCHASE_ENTITY_ORDER = [
    "skin_chigga_bball_team_black",
    "skin_chigga_bball_team_blue",
    "skin_chigga_bball_team_green",
    "skin_chigga_bball_team_purple",
    "skin_chigga_bball_team_red",
    "skin_chigga_fball_team_black",
    "skin_chigga_fball_team_green",
    "skin_chigga_fball_team_purple",
    "skin_chigga_fball_team_red",
    "skin_chigga_vamp",
    "skin_formal_fine_flea",
    "skin_mummified_mite",
    "skin_pinstripe_plague_boss",
    "skin_purple_velour_vandal",
    "soldier_lil_vamp_soldier",
    "soldier_soldier_0007_suit",
    "soldier_soldier_bball_blue",
    "soldier_soldier_bball_team_flame",
    "soldier_soldier_bball_team_green",
    "soldier_soldier_bball_team_purple",
    "soldier_soldier_bball_team_red",
    "soldier_soldier_franken_flea",
    "soldier_soldier_mummy_fit",
    "soldier_soldier_sour_prince",
    "soldier_soldier_team_black",
    "soldier_soldier_team_black_2",
    "soldier_soldier_team_blue",
    "soldier_soldier_team_green",
    "soldier_soldier_team_orange",
];

export function getLegendaryPurchaseEntity(skinId) {
    return LEGENDARY_PURCHASE_ENTITIES[skinId] || null;
}

export function getLegendaryPurchaseEntityByProductId(productId) {
    return Object.values(LEGENDARY_PURCHASE_ENTITIES).find(entity =>
        entity.productId === productId ||
        entity.googlePlayProductId === productId ||
        entity.steamProductId === productId
    ) || null;
}

export function getLegendaryPurchaseEntities(type = null) {
    return LEGENDARY_PURCHASE_ENTITY_ORDER
        .map(id => LEGENDARY_PURCHASE_ENTITIES[id])
        .filter(entity => entity && entity.active)
        .filter(entity => !type || entity.type === type);
}

export function validateLegendaryPurchaseCatalog(skins = {}) {
    const errors = [];
    const seenProductIds = new Set();
    const seenSteamItemDefIds = new Set();

    getLegendaryPurchaseEntities().forEach(entity => {
        const skin = skins[entity.skinId];
        if (!skin) errors.push(`Missing skin for purchase entity: ${entity.skinId}`);
        if (skin && skin.unlockType !== 'premium') errors.push(`${entity.skinId} is not marked premium`);
        if (skin && skin.rarity !== 'legendary') errors.push(`${entity.skinId} is not marked legendary`);
        if (!entity.productId) errors.push(`${entity.skinId} is missing productId`);
        if (seenProductIds.has(entity.productId)) errors.push(`Duplicate productId: ${entity.productId}`);
        seenProductIds.add(entity.productId);
        if (seenSteamItemDefIds.has(entity.steamItemDefId)) errors.push(`Duplicate Steam itemdefid: ${entity.steamItemDefId}`);
        seenSteamItemDefIds.add(entity.steamItemDefId);
    });

    return errors;
}